### ISSUE TITLE
Сurrency is not convertible

### ISSUE THREAD

**Issue by Anastasiia0707** [navid-farjad/weapp-public#17]
17.Settings:
During the checkout initial amount in EUR and final in the USD. 
Solution: You need to add currency conversion.
![Screenshot_13](https://user-images.githubusercontent.com/89030389/130284327-583a25d7-a1a0-490a-8988-04d7b968469c.png)
![Screenshot_8](https://user-images.githubusercontent.com/89030389/130284330-b5419bfb-cd37-40f5-bf8e-17a67c52f8a1.png)

**Comment by aachil** [comment]
@Anastasiia0707  please propose solutions as people who will work on the corrections need clear instructions
