### ISSUE TITLE
Description discrepancy 

### ISSUE THREAD

**Issue by Anastasiia0707** [navid-farjad/weapp-public#25]
25. Dashboard/Company Account.
Account description states that it demonstrates Daily screenshots. This is not true 
Solution: Company Account details  
![image](https://user-images.githubusercontent.com/89030389/129790035-43e88fb3-722b-4bbe-b4c6-05bba0bacae6.png)

**Comment by aachil** [comment]
@Anastasiia0707  please provide the exact change that you suggest in this way in order for everybody to understand 
![Screenshot_2](https://user-images.githubusercontent.com/89189416/130043276-10be609a-fc8d-41b8-abd3-b98d1cff6e56.jpg)

**Comment by aachil** [comment]
@Anastasiia0707  with what shall we replace that? 
When you identify an error or a change please submit the solution as well
